# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER Paulina Lach

# Update the repository sources list
RUN apt-get update

RUN apt-get -y install gcc

ADD ./hello.c /home/hello.c
RUN gcc /home/hello.c -o /home/hello.out

ENTRYPOINT /home/hello.out